### PR TITLE
Addition of a hex serial and removal or protected method.

### PR DESCRIPTION
**Pull request by pyrat**
Hi Nate,

I have added a method to certificate called hex_serial which returns a serial in the same format as openssl uses on the command line etc.

Also I found the <pre>read_extension_by_oid(oid)</pre> method useful for getting other extension values out of certificates so have made it an instance method instead of protected.

I have also added a test for the hex_serial method. 

What do you think?

Cheers,
Alastair

### CODE REVIEW

**Comment by nbibler** [comment]
Hey pyrat.  Sorry for the delayed response. :(

So, I like the hex serial.  I certainly think that's a good helper method to provide.

I'm curious about the removal of the protection on `read_extension_by_oid`.  That method was not intended to be publicly used (used from outside of the instance).  You mention that you found it useful for getting "other extension values."  Is there any reason not to make getting those other values additional instance methods on the Certificate?  It seems like opening the read_extension method is a bit dirty to me.

**Comment by nbibler** [comment]
Yeah, that `OpenSSL::BN` object is quite awkward.  I don't know your use case, maybe you're just displaying the hex serial, but I was wondering if there were a better way to extend the `serial` result to invisibly work better for comparisons and whatnot. Because, displaying Ruby Integers in hex is somewhat common, at least within Rails, and there are several support functions already available through Ruby, ActiveSupport, and other gems for doing `1.to_s(16)`, as you've already shown in your pull request. So, I was wondering if something like the following would be nicer (automatically determining equality based on the input, for example):

``` ruby
certificate = OpenSSL::X509::Certificate.new('…')

if certificate.serial == 'OEA4BB'
  puts 'Found the certificate!'
end
```

But, alas, the above currently throws an exception:

``` ruby
TypeError: Cannot convert into OpenSSL::BN
    from (irb):34:in `eql?'
    from (irb):34
```

And that may not even meet your use case.

Generally, I've been trying to provide convenience methods in OpenSSLExtensions to access data within the OpenSSL library that requires a convoluted action to properly get at it (building a sorted certificate chain, finding the certificate name, listing subject alternative names, determining if it's a root or even an issuing authority, etc).  The `hex_serial` method you've submitted isn't _incredibly_ difficult for someone with some knowledge of Ruby to come about on on their own, and it adds the cost of another Certificate method.  I wonder if extending the `BN` to carry a "to_hex" method might also solve the problem and be more usable?

``` ruby
certificate = OpenSSL::X509::Certificate.new('…')
if certificate.serial.to_hex == 'OEA4BB'
  puts 'Found the certificate!'
end
```

Anyway, let me know your thoughts.

**Comment by pyrat** [comment]
Hi Nathan,

`hex_serial`

 `.serial.to_hex` sounds good. Do we then need to add a `to_hex` method to the Integer class?

`read_extension_by_oid`

I have been working with OSCP (http://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) and CRL (http://en.wikipedia.org/wiki/Certificate_revocation_list). To get this information I have been using `read_extension_by_oid` for `authorityInfoAccess` and `crlDistributionPoints`. 

There is `OpenSSL::CRL` which works well and I can just check serial numbers with the standard .serial method (so we shouldnt actually change its behaviour) but `OpenSSL::OCSP` doesnt work for me so I need to generate some funky openssl shell commands which requires the serial to be in this hex format. Hope this explains my use case. Maybe we can add `authorityInfoAccess` and `crlDistributionPoints` as certificate methods?

**Comment by nbibler** [comment]
No, we wouldn't need to add `to_hex` to the `Integer` class, but instead to the [`OpenSSL::BN`](https://github.com/ruby/ruby/blob/trunk/ext/openssl/ossl_bn.c) class.  It looks like `certificate.serial` returns a `BN` instance, which I believe stands for "Big Number."  This object seems to encapsulate some other logic, like randomization and GCD.

Yeah, I think that potentially adding accessors for the authority info and distribution points sounds fair.  I, honestly, don't know enough about what that information is used for to have a lot of valid input on it.  But, I do like the idea of adding accessors directly to that data more than just opening the `read_extensions_by_oid` method.

**Comment by pyrat** [comment]
Hi Nate,

I have implemented what we discussed previously and have added it to the pull request. Please review and alter as you will.

Cheers,
Alastair

**Comment by nbibler** [comment]
Thanks, @pyrat! :)  I've pushed it in and released [version 1.2.0](http://github.com/envylabs/openssl-extensions/compare/v1.1.0...v1.2.0).

**Comment by pyrat** [comment]
Excellent good stuff, is the travis builds a new addition as well? I like it.

On 3 November 2011 21:03, Nathaniel Bibler
reply@reply.github.com
wrote:

**Comment by nbibler** [comment]
It is.  I added it last night.  Sadly, travis doesn't seem to currently work well with Organization repositories, so I had to fork it for the sole purpose of having travis test against my fork. :-\  Not ideal, but it looks like they're working on it.

I've got it testing against a handful of implementations.  I was hoping it would also work for JRuby, but looking at their implementation of OpenSSL (at [jruby-ossl](https://github.com/jruby/jruby-ossl)), it's unlikely it'll ever happen.

**Pull request merged**
